import Footer from "../components/Footer";
import "../../src/app/globals.css";
import Head from "next/head";
export default function page2() {
  return (
    <div className="flex justify-center items-center h-screen">
      <Head>
        <title>Task Manager</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1 className="text-3xl font-bold">Page 2</h1>
      <Footer />
    </div>
  );
}
